version: '3.8'

services:
  storefront:
    build:
      context: .
      dockerfile: ./apps/storefront/Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "5173:5173"
    volumes:
    - ./apps/storefront:/app/apps/storefront
    - ./packages:/app/packages
    environment:
      - NODE_ENV=development
      # Enable polling for HMR to function correctly with volumes
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    stdin_open: true
    tty: true
    networks:
      - turborepo-network

volumes:
  turborepo-cache:

networks:
  turborepo-network:
    driver: bridge
