version: '3.8'

services:
  storefront:
    build:
      context: .
      dockerfile: ./apps/storefront/Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "5173:5173"
    volumes:
    - ./apps/storefront:/app/apps/storefront
    - ./packages:/app/packages
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - products
    networks:
      - turborepo-network

  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "5174:5174"
    volumes:
      - ./apps/admin:/app/apps/admin
      - ./packages:/app/packages
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    stdin_open: true
    tty: true
    depends_on:
      - products
    networks:
      - turborepo-network

  products:
    build:
      context: .
      dockerfile: ./services/products/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./services/products/src:/app/src
      - ./services/products/package.json:/app/package.json
      - ./services/products/tsconfig.json:/app/tsconfig.json
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@products-db:5432/products
    depends_on:
      - products-db
    networks:
      - turborepo-network
    command: ["npm", "run", "start"]

  products-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=products
    ports:
      - "5432:5432"
    volumes:
      - products-db-data:/var/lib/postgresql/data
    networks:
      - turborepo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  products-db-data:

networks:
  turborepo-network:
    driver: bridge
